import {
  pgTable,
  uuid,
  text,
  timestamp,
  integer,
  boolean,
  numeric,
  pgEnum,
} from "drizzle-orm/pg-core";

export const budgetCategoryEnum = pgEnum("budget_category", [
  "transport",
  "stay",
  "food",
  "activity",
  "other",
]);

export const shareAccessLevelEnum = pgEnum("share_access_level", [
  "view",
  "edit",
]);

export const profiles = pgTable("profiles", {
  id: uuid("id").primaryKey(),
  displayName: text("display_name"),
  avatarUrl: text("avatar_url"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export const trips = pgTable("trips", {
  id: uuid("id").primaryKey().defaultRandom(),
  ownerId: uuid("owner_id").notNull(),
  title: text("title").notNull().default("Untitled Trip"),
  startDate: timestamp("start_date", { withTimezone: true }),
  endDate: timestamp("end_date", { withTimezone: true }),
  currency: text("currency").notNull().default("USD"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
});

export const companions = pgTable("companions", {
  id: uuid("id").primaryKey().defaultRandom(),
  tripId: uuid("trip_id")
    .notNull()
    .references(() => trips.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  color: text("color"),
  avatarUrl: text("avatar_url"),
});

export const checkpoints = pgTable("checkpoints", {
  id: uuid("id").primaryKey().defaultRandom(),
  tripId: uuid("trip_id")
    .notNull()
    .references(() => trips.id, { onDelete: "cascade" }),
  orderIndex: integer("order_index").notNull().default(0),
  locationName: text("location_name").notNull(),
  latitude: numeric("latitude", { precision: 10, scale: 7 }),
  longitude: numeric("longitude", { precision: 10, scale: 7 }),
  arrivalDate: timestamp("arrival_date", { withTimezone: true }),
  departureDate: timestamp("departure_date", { withTimezone: true }),
  notes: text("notes"),
});

export const stays = pgTable("stays", {
  id: uuid("id").primaryKey().defaultRandom(),
  checkpointId: uuid("checkpoint_id")
    .notNull()
    .references(() => checkpoints.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  address: text("address"),
  latitude: numeric("latitude", { precision: 10, scale: 7 }),
  longitude: numeric("longitude", { precision: 10, scale: 7 }),
  costPerNight: numeric("cost_per_night", { precision: 12, scale: 2 }),
  nights: integer("nights").notNull().default(1),
});

export const budgetItems = pgTable("budget_items", {
  id: uuid("id").primaryKey().defaultRandom(),
  tripId: uuid("trip_id")
    .notNull()
    .references(() => trips.id, { onDelete: "cascade" }),
  checkpointId: uuid("checkpoint_id").references(() => checkpoints.id, {
    onDelete: "set null",
  }),
  category: budgetCategoryEnum("category").notNull().default("other"),
  amount: numeric("amount", { precision: 12, scale: 2 }).notNull(),
  currency: text("currency").notNull().default("USD"),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
});

export const notes = pgTable("notes", {
  id: uuid("id").primaryKey().defaultRandom(),
  tripId: uuid("trip_id")
    .notNull()
    .references(() => trips.id, { onDelete: "cascade" }),
  checkpointId: uuid("checkpoint_id").references(() => checkpoints.id, {
    onDelete: "cascade",
  }),
  body: text("body").notNull(),
});

export const tripShareTokens = pgTable("trip_share_tokens", {
  id: uuid("id").primaryKey().defaultRandom(),
  tripId: uuid("trip_id")
    .notNull()
    .references(() => trips.id, { onDelete: "cascade" }),
  token: text("token").notNull().unique(),
  accessLevel: shareAccessLevelEnum("access_level").notNull().default("view"),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
});

export type Trip = typeof trips.$inferSelect;
export type NewTrip = typeof trips.$inferInsert;
export type Checkpoint = typeof checkpoints.$inferSelect;
export type BudgetItem = typeof budgetItems.$inferSelect;
export type Companion = typeof companions.$inferSelect;
export type Stay = typeof stays.$inferSelect;
export type Note = typeof notes.$inferSelect;
export type TripShareToken = typeof tripShareTokens.$inferSelect;
