import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { budgetItems } from "@/lib/db/schema";
import { getUser } from "@/lib/auth/server";
import { createBudgetItemSchema } from "@/lib/validation/trip";

interface RouteParams {
  params: Promise<{ id: string }>;
}

export async function POST(request: Request, { params }: RouteParams) {
  const { id: tripId } = await params;
  const user = await getUser();
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await request.json();
  const parsed = createBudgetItemSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });
  }

  const [item] = await db
    .insert(budgetItems)
    .values({
      tripId,
      checkpointId: parsed.data.checkpointId,
      category: parsed.data.category,
      amount: parsed.data.amount.toString(),
      currency: parsed.data.currency,
      isAutoGenerated: parsed.data.isAutoGenerated,
    })
    .returning();

  return NextResponse.json(item, { status: 201 });
}
