import { z } from "zod";

export const budgetCategorySchema = z.enum([
  "transport",
  "stay",
  "food",
  "activity",
  "other",
]);

export const shareAccessLevelSchema = z.enum(["view", "edit"]);

export const createTripSchema = z.object({
  title: z.string().min(1).max(200).default("Untitled Trip"),
  currency: z.string().length(3).default("USD"),
  startDate: z.string().datetime().optional(),
  endDate: z.string().datetime().optional(),
});

export const updateTripSchema = createTripSchema.partial();

export const createCompanionSchema = z.object({
  name: z.string().min(1).max(100),
  color: z.string().max(20).optional(),
  avatarUrl: z.string().url().optional(),
});

export const createCheckpointSchema = z.object({
  locationName: z.string().min(1).max(300),
  latitude: z.number().min(-90).max(90).optional(),
  longitude: z.number().min(-180).max(180).optional(),
  arrivalDate: z.string().datetime().optional(),
  departureDate: z.string().datetime().optional(),
  notes: z.string().max(5000).optional(),
  orderIndex: z.number().int().min(0).optional(),
});

export const updateCheckpointSchema = createCheckpointSchema.partial();

export const createBudgetItemSchema = z.object({
  category: budgetCategorySchema.default("other"),
  amount: z.number().positive(),
  currency: z.string().length(3).default("USD"),
  checkpointId: z.string().uuid().optional(),
  isAutoGenerated: z.boolean().default(false),
});

export const createNoteSchema = z.object({
  body: z.string().min(1).max(10000),
  checkpointId: z.string().uuid().optional(),
});

export const createShareTokenSchema = z.object({
  accessLevel: shareAccessLevelSchema.default("view"),
  expiresAt: z.string().datetime().optional(),
});

export const linkIdentitySchema = z.object({
  email: z.string().email(),
  password: z.string().min(8).max(128),
});

export type CreateTripInput = z.infer<typeof createTripSchema>;
export type UpdateTripInput = z.infer<typeof updateTripSchema>;
export type CreateCompanionInput = z.infer<typeof createCompanionSchema>;
export type CreateCheckpointInput = z.infer<typeof createCheckpointSchema>;
export type CreateBudgetItemInput = z.infer<typeof createBudgetItemSchema>;
export type CreateNoteInput = z.infer<typeof createNoteSchema>;
export type CreateShareTokenInput = z.infer<typeof createShareTokenSchema>;
