"use client";

import { useState } from "react";
import { useTripStore } from "@/stores/trip-store";
import type { BudgetItem } from "@/lib/db/schema";

const CATEGORIES = ["transport", "stay", "food", "activity", "other"] as const;

export function BudgetEditor({ tripId }: { tripId: string }) {
  const budgetItems = useTripStore((s) => s.budgetItems);
  const addBudgetItem = useTripStore((s) => s.addBudgetItem);
  const [showForm, setShowForm] = useState(false);
  const [category, setCategory] = useState<string>("other");
  const [amount, setAmount] = useState("");

  function handleAdd() {
    const parsed = parseFloat(amount);
    if (isNaN(parsed) || parsed <= 0) return;

    const item: BudgetItem = {
      id: crypto.randomUUID(),
      tripId,
      checkpointId: null,
      category: category as BudgetItem["category"],
      amount: parsed.toString(),
      currency: "USD",
      isAutoGenerated: false,
    };
    addBudgetItem(item);
    setAmount("");
    setShowForm(false);
  }

  const total = budgetItems.reduce((sum, item) => sum + Number(item.amount), 0);

  return (
    <section className="border border-border-subtle rounded-lg bg-surface p-spacing-gap-md">
      <div className="flex items-center justify-between">
        <h2 className="text-headline-md text-primary">Budget — ${total.toFixed(2)}</h2>
        <button
          type="button"
          onClick={() => setShowForm(true)}
          className="bg-primary text-on-primary px-3 py-1.5 rounded text-label-md font-medium hover:opacity-90 transition-opacity"
        >
          Add item
        </button>
      </div>

      {showForm && (
        <div className="mt-4 space-y-3 border border-border-subtle rounded p-4">
          <div>
            <label className="block text-label-md text-text-secondary mb-1">Category</label>
            <select
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="w-full px-3 py-2 border border-border-subtle rounded text-body-md text-primary bg-bg-canvas focus:border-primary focus:outline-none transition-soft"
            >
              {CATEGORIES.map((c) => (
                <option key={c} value={c}>
                  {c.charAt(0).toUpperCase() + c.slice(1)}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-label-md text-text-secondary mb-1">Amount ($)</label>
            <input
              type="number"
              step="0.01"
              min="0"
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              placeholder="0.00"
              className="w-full px-3 py-2 border border-border-subtle rounded text-body-md text-primary bg-bg-canvas focus:border-primary focus:outline-none transition-soft"
            />
          </div>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={handleAdd}
              className="bg-primary text-on-primary px-4 py-2 rounded text-body-md font-medium hover:opacity-90 transition-opacity"
            >
              Add
            </button>
            <button
              type="button"
              onClick={() => setShowForm(false)}
              className="border border-border-subtle px-4 py-2 rounded text-body-md text-text-secondary hover:bg-hover-fill transition-colors"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {budgetItems.length === 0 && !showForm && (
        <p className="mt-4 text-body-md text-text-secondary">No budget items yet. Add your first expense.</p>
      )}

      <ul className="mt-4 space-y-1">
        {budgetItems.map((item) => (
          <li
            key={item.id}
            className="flex items-center justify-between px-3 py-2 text-body-md"
          >
            <span className="text-text-secondary capitalize">{item.category}</span>
            <span className="font-medium text-primary">${Number(item.amount).toFixed(2)}</span>
          </li>
        ))}
      </ul>
    </section>
  );
}
