"use client";

import { useState } from "react";
import { useTripStore } from "@/stores/trip-store";
import type { BudgetItem } from "@/lib/db/schema";

const CATEGORIES = ["transport", "stay", "food", "activity", "other"] as const;

export function BudgetEditor({ tripId }: { tripId: string }) {
  const budgetItems = useTripStore((s) => s.budgetItems);
  const addBudgetItem = useTripStore((s) => s.addBudgetItem);
  const [showForm, setShowForm] = useState(false);
  const [category, setCategory] = useState<string>("other");
  const [amount, setAmount] = useState("");
  function handleAdd() {
    const parsed = parseFloat(amount);
    if (isNaN(parsed) || parsed <= 0) return;

    const item: BudgetItem = {
      id: crypto.randomUUID(),
      tripId,
      checkpointId: null,
      category: category as BudgetItem["category"],
      amount: parsed.toString(),
      currency: "USD",
      isAutoGenerated: false,
    };
    addBudgetItem(item);
    setAmount("");
    setShowForm(false);
  }

  const total = budgetItems.reduce((sum, item) => sum + Number(item.amount), 0);

  return (
    <section className="rounded-xl border border-zinc-200 bg-white p-6">
      <div className="flex items-center justify-between">
        <h2 className="font-semibold text-zinc-900">
          Budget — ${total.toFixed(2)}
        </h2>
        <button
          type="button"
          onClick={() => setShowForm(true)}
          className="rounded-lg bg-teal-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-teal-700"
        >
          Add item
        </button>
      </div>

      {showForm && (
        <div className="mt-4 space-y-3 rounded-lg border border-zinc-100 p-4">
          <div>
            <label className="block text-xs font-medium text-zinc-600">Category</label>
            <select
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="mt-1 w-full rounded-lg border border-zinc-300 px-3 py-2 text-sm focus:border-teal-500 focus:outline-none focus:ring-1 focus:ring-teal-500"
            >
              {CATEGORIES.map((c) => (
                <option key={c} value={c}>
                  {c.charAt(0).toUpperCase() + c.slice(1)}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-xs font-medium text-zinc-600">Amount ($)</label>
            <input
              type="number"
              step="0.01"
              min="0"
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              placeholder="0.00"
              className="mt-1 w-full rounded-lg border border-zinc-300 px-3 py-2 text-sm focus:border-teal-500 focus:outline-none focus:ring-1 focus:ring-teal-500"
            />
          </div>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={handleAdd}
              className="rounded-lg bg-teal-600 px-4 py-2 text-xs font-medium text-white hover:bg-teal-700"
            >
              Add
            </button>
            <button
              type="button"
              onClick={() => setShowForm(false)}
              className="rounded-lg border border-zinc-300 px-4 py-2 text-xs font-medium text-zinc-600 hover:bg-zinc-50"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      {budgetItems.length === 0 && !showForm && (
        <p className="mt-4 text-sm text-zinc-500">
          No budget items yet. Add your first expense.
        </p>
      )}

      <ul className="mt-4 space-y-1">
        {budgetItems.map((item) => (
          <li
            key={item.id}
            className="flex items-center justify-between rounded-lg px-3 py-2 text-sm"
          >
            <span className="text-zinc-600 capitalize">{item.category}</span>
            <span className="font-medium text-zinc-900">
              ${Number(item.amount).toFixed(2)}
            </span>
          </li>
        ))}
      </ul>
    </section>
  );
}
